import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const source = (await readFile(path.join(projectRoot, 'supabase/new_project_init.sql'), 'utf8')).replace(/\r\n/g, '\n');
const identity = (await readFile(path.join(projectRoot, 'cloudbase/identity.sql'), 'utf8')).replace(/\r\n/g, '\n').trim();
const marker = '-- ===== 001_studychat.sql =====';
if (!source.includes(marker)) throw new Error('Missing Supabase bootstrap marker; review the schema source.');
let business = source.slice(source.indexOf(marker));

// These bounded transformations were reviewed at every occurrence. All
// business transactions, actor checks, locks, snapshots, leases and grants remain
// byte-for-byte identical. Refuse new/unexpected auth dependencies for review.
for (const [from, to, expected] of [
  ['references auth.users(id)', 'references public.app_users(id)', 7],
  ['(select auth.uid())', '(select public.app_current_user_id())', 4],
  // Remove inherited PUBLIC defaults too, before granting the deliberate
  // authenticated own-read columns. CloudBase defaults need not match Supabase.
  ['public.conversations, public.messages, public.request_events from anon, authenticated;',
    'public.conversations, public.messages, public.request_events from public, anon, authenticated;', 1],
]) {
  const count = business.split(from).length - 1;
  if (count !== expected) throw new Error(`Expected ${expected} reviewed occurrences of ${from}; found ${count}.`);
  business = business.replaceAll(from, to);
}
if (/\bauth\./i.test(business)) throw new Error('New native auth dependency; adapt it explicitly before generating CloudBase SQL.');

const header = `-- StudyChat: initialize a NEW, EMPTY CloudBase PostgreSQL environment ONCE.
-- Execute through the CloudBase SQL Editor / ExecutePGSql as cloudbase_admin.
-- ExecutePGSql accepts one statement; this whole file is one atomic DO block.
-- This does NOT migrate users or data and does NOT modify platform auth.*.
-- Generated by node cloudbase/scripts/build-schema.mjs; edit identity.sql or
-- the canonical Supabase migrations, review adaptations, then regenerate.
-- After website admin login, locate its app_users UUID by CloudBase subject and
-- add that UUID to admin_users. Never grant an administrator by student number.
-- Existing-data imports: seed business user UUIDs, import public business rows,
-- then link each identity only after independent proof of the old/new accounts.
-- Preserve CONFIG_ENCRYPTION_KEY when importing encrypted model settings.
`;
const target = path.join(projectRoot, 'cloudbase/new_project_init.sql');
let body = `-- ===== CloudBase identity layer =====\n${identity}\n\n${business}`;
// ExecutePGSql's native channel accepts one SQL statement per call. An outer DO
// block preserves all DDL/PLpgSQL definitions as one atomic setup transaction.
// Only the nine reviewed top-level migration transaction delimiters change.
for (const delimiter of ['begin;', 'commit;']) {
  const pattern = new RegExp(`^${delimiter}$`, 'gm');
  const count = [...body.matchAll(pattern)].length;
  if (count !== 9) throw new Error(`Expected 9 reviewed top-level ${delimiter} markers; found ${count}.`);
  body = body.replace(pattern, '');
}
if (body.includes('$studychat_init$')) throw new Error('Conflicting outer SQL dollar delimiter.');
const output = `${header}\nDO $studychat_init$\nBEGIN\n${body.trim()}\nEND;\n$studychat_init$;\n`;
if (process.argv.includes('--check')) {
  const existing = (await readFile(target, 'utf8')).replace(/\r\n/g, '\n');
  if (existing !== output) throw new Error('CloudBase bootstrap is stale. Run node cloudbase/scripts/build-schema.mjs and review the diff.');
  process.stdout.write('CloudBase schema matches reviewed source.\n');
} else {
  await writeFile(target, output, 'utf8');
  process.stdout.write('Generated cloudbase/new_project_init.sql (7 UUID foreign keys, 4 identity policies, 1 PUBLIC revoke adapted).\n');
}
